apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-migrate-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: project-migrate-backend
  template:
    metadata:
      labels:
        app: project-migrate-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8000
