apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-migrate-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: project-migrate-frontend
  template:
    metadata:
      labels:
        app: project-migrate-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80
