apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-migrate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-migrate-backend
  template:
    metadata:
      labels:
        app: project-migrate-backend
    spec:
      containers:
        - name: backend
          image: your-registry/project-migrate-backend:0.1.0
          ports:
            - containerPort: 8000
