apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-migrate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-migrate-frontend
  template:
    metadata:
      labels:
        app: project-migrate-frontend
    spec:
      containers:
        - name: frontend
          image: your-registry/project-migrate-frontend:0.1.0
          ports:
            - containerPort: 80
