apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-migrate-ingress
spec:
  rules:
    - host: project-migrate.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-migrate-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: project-migrate-backend
                port:
                  number: 8000
